apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: desktop-systems
  description: A collection of all systems
spec:
  targets:    
    - ./systems/desktop-resource-field-appoiment.yaml
    - ./systems/desktop-resource-field-system.yaml
