apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: examples-apis
  description: A collection of all Backstage example APIs
spec:
  targets:
    - ./apis/customer-service-barramento-api.yaml 
