apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: apis-salesforce
  description: A collection of all Backstage example APIs
spec:
  targets:    
    - ./apis/salesforce/field-barramento-api.yaml
    - ./apis/salesforce/field-internal-gateway.yaml
    - ./apis/oss/websvc-api.yaml
    - ./apis/oss/massive-api.yaml
    - ./apis/oss/messaging.yaml
    - ./apis/oss/resource-inventory-api.yaml