apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: desktop-customer-payment
  description: Configuração e administração de métodos de pagamento como cartões de crédito, débito, transferências bancárias, e-wallets, entre outros
  title: Artists
  links:
    - url: https://desktop.atlassian.net/payment/
      title: Domain Readme
    - url: https://desktop.atlassian.net/payment/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: team-payment
  subdomainOf: Customer
