apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-mq
  description: Apache Kafka é uma plataforma open-source de processamento de streams desenvolvida pela Apache Software Foundation, escrita em Scala e Java. O projeto tem como objetivo fornecer uma plataforma unificada, de alta capacidade e baixa latência para tratamento de dados em tempo real. 
spec:
  type: database
  owner: operacoes
