apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: barramento-service
links:
  - url: https://desktop.atlassian.net/wiki/spaces/SS/pages/137396225/Documenta+o+Barramento+-+Service
    title: Confluence
    icon: code
spec:
  type: openapi
  lifecycle: producao
  owner: team-deskforce
  system: interaction
  definition:
    $text: ./barramento-service-api-swagger.yaml
    

