apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: barramento-field-api
  description: The petstore API
  tags:
    - store
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: team-deskforce
  definition:
    $text: ./petstore.oas.yaml
