apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: relationship
  description: Gerencia o ciclo de vida do cliente 
  tags:
    - portal
spec:
  domain: customer
  owner: desktop-corp
  
