apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: appointment
  description: Relacionado ao ERP empresarial, contas a receber, contas a pagar, etc.
  tags:
    - portal
spec:
  domain: resource-field
  owner: desktop-corp
  
