apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: security
  description: Gestão de segurança e risco empresarial
  tags:
    - portal
spec:
  domain: enterprise
  owner: desktop-corp
  
