apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: resource-usage
  description: Processa eventos de mediação relacionados aos recursos
  tags:
    - resource
spec:
  domain: resource
  owner: desktop-corp
  
