apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: usage
  description: Gerencia e controla o uso dos serviços pelos clientes
  tags:
    - portal
specs:
  domain: service
  owner: desktop-corp
  
