apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: inventory
  description: Relaciona e sincroniza os itens do catálogo de recursos com os serviços aos quais estão associados
  tags:
    - portal
spec:
  domain: service
  owner: desktop-corp
  
