apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: resource-inventory-api
  description: websvc-api      
  links:
  - url: https://bitbucket.org/desktop/desktop-resource-inventory-api
    title: Confluence
    icon: code
  - url: https://bitbucket.org/desktop/websvc/src/main/
    title: Repositório
    icon: code
  tags:    
    - websvc
spec:
  type: openapi
  lifecycle: production  
  owner: team-oss
  system: legacy-oss
  dependsOn: ['resource:admin-db']
  consumesApis:
    - api:websvc-api
