apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: resource-inventory-api
  description: websvc-api      
  links:
  - url: https://bitbucket.org/desktop/desktop-resource-inventory-api
    title: Confluence
    icon: code
  - url: https://bitbucket.org/desktop/websvc/src/main/
    title: Repositório
    icon: code
  tags:    
    - websvc
spec:
  type: openapi
  lifecycle: production  
  owner: team-oss
  system: legacy-oss
  dependsOn: ['resource:admin-db']
  consumesApis:
    - api:websvc-api
  definition: |
      openapi: "3.0.0"
      info:
        version: 1.0.0
        title: resource-inventory-api
        description: Api para listagem de inventário de recursos
        license:
          name: © 2021 DESKTOP INTERNET SERVICES | CNPJ 08.170.849/0001-15
          url: http://www.desktop.com.br        
      servers:
        - url: http://api-v2.desktop.com.br/v1
      paths:
        /protocol:
          get:
            summary: Get olts
